dataset: AID-imagenet
dataset_args: {split: test}

load: ./meta-baseline/save/classifier_AID-imagenet_resnet12_moreepoch/max-va.pth

# Replace load with load_encoder for loading the encoder only (e.g. for testing Classifier-Baseline)
