train_dataset: AID-imagenet
train_dataset_args: {split: train}
tval_dataset: AID-imagenet
tval_dataset_args: {split: test}
val_dataset: AID-imagenet
val_dataset_args: {split: val}

model: meta-baseline
model_args: 
    encoder: resnet12
    encoder_args: {}
load_encoder: ./meta-baseline/save/classifier_AID-imagenet_resnet12_moreepoch/epoch-last.pth

n_way: 5
n_shot: 1
n_query: 15
train_batches: 200
ep_per_batch: 2
fs_batch: 100

max_epoch: 20
optimizer: sgd
optimizer_args: {lr: 0.001, weight_decay: 5.e-3}

visualize_datasets: false