train_dataset: NWPU-imagenet
train_dataset_args: {split: train, augment: resize}
val_dataset: NWPU-imagenet
val_dataset_args: {split: train_phase_val}
fs_dataset: NWPU-imagenet
fs_dataset_args: {split: test}
eval_fs_epoch: 5

model: classifier
model_args:
    encoder: transformer   # 
    encoder_args: {input_resolution: 64, patch_size: 8, width: 16, layers: 24, heads: 8, output_dim: 512}
    classifier: linear-classifier 
    classifier_args: {n_classes: 25}


fs_batch: 200
fs_ep_per_epoch: 4
batch_size: 128
max_epoch: 200
optimizer: sgd
optimizer_args: {lr: 0.01, weight_decay: 5.e-4, milestones: [150]}

save_epoch: 5
visualize_datasets: false