train_dataset: UCM-imagenet
train_dataset_args: {split: train, augment: resize}
val_dataset: UCM-imagenet
val_dataset_args: {split: train_phase_val}
fs_dataset: UCM-imagenet
fs_dataset_args: {split: test}
eval_fs_epoch: 5

model: classifier
model_args:
    encoder: resnet12
    encoder_args: {}
    classifier: linear-classifier 
    classifier_args: {n_classes: 10}

fs_batch: 1
fs_ep_per_epoch: 1
batch_size: 16
max_epoch: 120
optimizer: sgd
optimizer_args: {lr: 0.1, weight_decay: 5.e-4, milestones: [100]}

save_epoch: 10
visualize_datasets: true