train_dataset: AID-imagenet
train_dataset_args: {split: train, augment: resize}
val_dataset: AID-imagenet
val_dataset_args: {split: train_phase_val}
fs_dataset: AID-imagenet
fs_dataset_args: {split: test}
eval_fs_epoch: 5
load: ./meta-baseline/save/classifier_AID-imagenet_resnet12_DA,Rsz128_02/epoch-last.pth
model: classifier
model_args:
    encoder: resnet12
    encoder_args: {}
    classifier: linear-classifier 
    classifier_args: {n_classes: 15}


fs_batch: 200
fs_ep_per_epoch: 4
batch_size: 128
max_epoch: 100
optimizer: sgd
optimizer_args: {lr: 0.1, weight_decay: 5.e-4, milestones: [90]}

save_epoch: 5
visualize_datasets: false